name: Build Arch Package

on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build-arch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Arch package in container
      env:
        LINUXTOYS_VERSION: ${{ steps.read_version_file.outputs.version }}
      run: |
        docker run --rm -v "$PWD:/workspace" -w /workspace archlinux:base-devel \
        bash -c "
          pacman -Syu --noconfirm &&
          pacman -S --needed --noconfirm base-devel wget libnewt alacritty git &&
          useradd -m builder &&
          chown -R builder . &&
          su builder -c 'cd src/buildfiles/pkgbuild && makepkg -s --noconfirm' &&
          cp src/buildfiles/pkgbuild/*.pkg.tar.* ./
        "

    - name: Upload Arch package artifact
      uses: actions/upload-artifact@v4
      with:
        name: archlinux-package
        path: ./*.pkg.tar.*

